### ISSUE TITLE
Create`s Windmill bug

### ISSUE THREAD

**Issue by CapNapu** [MCTeamPotato/Kasualix-Issue-Tracker#107]
This bug only occurs when you get far enough away from a windmill in the Create mod. Apparently it "fixes" itself if you get close enough, but it is not permanent.

This bug comes from Magnesium/Rubidium Extras, so it also happens with Embeddium Extras (I`ve made the post here as the original mod is no longer being supported).

![Bug](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110067479/b43c29d3-dca8-4f25-b6d1-6448a5659f21)

**Comment by Kasualix** [comment]
This is happening because Embeddium Extras is avoiding rendering entities/tile entities that is far from player.
In 1.11.7, this culling will no longer take effect on Create entities anymore because I have added them to the config blacklist, you may need to remove the old config and generate a new one to make it work.

**Comment by Kasualix** [comment]
[File uploaded](https://legacy.curseforge.com/minecraft/mc-mods/embeddium-extras/files/4982105), thanks for your report
