### ISSUE TITLE
1.12.2的1.8.8崩溃

### ISSUE THREAD

**Issue by ukmojb** [MCTeamPotato/Kasualix-Issue-Tracker#42]
[crash-2023-08-28_16.53.29-client.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12452626/crash-2023-08-28_16.53.29-client.txt)

**Comment by Kasualix** [comment]
@Ecdcaeb

**Comment by Kasualix** [comment]
已分离，我这不再收1122的issue

**Comment by Ecdcaeb** [comment]
https://github.com/Ecdcaeb/Redirectionor/issues

**Comment by Ecdcaeb** [comment]
Caused by: java.lang.NoClassDefFoundError: twilightforest/tileentity/spawner/TileEntityTFFinalBossSpawner$Anonymous$3f8eef17c0a34f65aa597c10a5e03e30
但是查证发现暮色森林原版中Anonymous是不存在的，有mod对TileEntityTFFinalBossSpawner进行了修改。
Hileb没有办法复现它。
这个Debug版可能会获得更多日志信息。
https://www.mcmod.cn/download/11295.html
:
redirectionor-1.12.2-1.8.8-debug.jar

**Comment by Ecdcaeb** [comment]
@ukmojb ?

**Comment by Ecdcaeb** [comment]
问题解决了吗？

**Comment by ukmojb** [comment]
> 问题解决了吗？
抱歉，上周我已经前往了学校，另外请问是图片中的这个版本吗

![屏幕截图 2023-09-02 114044](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/105061290/6420ef03-0c75-454d-9c77-b10b38b5ca99)
