### ISSUE TITLE
[DoesPotatoTick] Discrepancy with SolidMobs mod

### ISSUE THREAD

**Issue by Cixon** [MCTeamPotato/Kasualix-Issue-Tracker#47]
### Log (line 3,494)
[latest.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12481643/latest.log)

**Mod Resources:**
https://legacy.curseforge.com/minecraft/mc-mods/solid-mobs/files/4727437
https://legacy.curseforge.com/minecraft/mc-mods/earth-mobs/files/4344148
-
https://www.curseforge.com/minecraft/mc-mods/doespotatotick/files/4623357
https://www.curseforge.com/minecraft/mc-mods/difficult-raids/files/4578894

_Forge - 40.2.8_
_1.18.2_

**Comment by Cixon** [comment]
### This issue is likely found in modern iterations of DoesPotatoTick when using SolidMobs mod such as 1.20.1 and 1.19.x

**Comment by Kasualix** [comment]
https://github.com/Traben-0/solid_mobs/issues/20
Did removing DPT fix it?

**Comment by Cixon** [comment]
> [Traben-0/solid_mobs#20](https://github.com/Traben-0/solid_mobs/issues/20) Did removing DPT fix it? In the log you provide there, DPT "is missing".

Not necessarily, I just ran a test without Ice and Fire and encountered similar results to other mobs. This time, a experience orb... that ticket I made is unrelated to this one.

See Results below:
[crash-2023-08-31_23.17.08-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12494228/crash-2023-08-31_23.17.08-server.txt)

Log (line 14,125):
[debug.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12494236/debug.log)

**Comment by Cixon** [comment]
Basically, I got a message prompt from DPT saying something was removed due to wrongful ticking and my character starting freezing in place and the client slowly but surely decayed like last time but the only difference in this test was without IaF mod.

**Comment by Kasualix** [comment]
Your testing seems a bit chaotic, and I believe you should organize it better. In this issue, the latest.log you submitted contains mod information for iceandfire, dpt, and solid mobs. In the crash report you handed over to Traben, it includes mod information for iceandfire and solid mobs, but there's no mention of dpt. However, in the crash report and debug.log you submitted in the second part of this issue, iceandfire disappears, leaving only dpt and solid mobs. So far, I don't think this crash is related to iceandfire and doespotatotick in any way.

Additionally, I suggest that you create a new world every time you test, rather than entering an existing world. Strangely, when dpt removes entities that cause tick errors due to other mods, it should print error stack traces in the log, but the logs you provided don't seem to contain them.

**Comment by Cixon** [comment]
You can run the tests yourself if you feel my diagnosis is improper but I strongly believe there’s a discrepancy with Solid Mobs and DPT. Rather it’s Traben’s mod at fault or DPT; it’s unsure since I’m no programmer.

All I know is, DPT never caused any disruption nor did IaF prior to adding Solid Mobs. Running tests with both of them singled out, alludes SolidMobs struggles with either or.

**Comment by Cixon** [comment]
Also, I did create a new world with my tests aside from Traben’s ticket as I felt it wasn’t necessary considering the entities I was testing was within my vicinity but I guess I could run that test another time but properly.

**Comment by Kasualix** [comment]
After my own test now I believe it's iceandfire & solid mobs and has nothing to do with dpt.
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110756250/1f388bfe-610f-4263-a33d-45a7d70e136d)
with these mods I can stably reproduce the crash you provide.
To reproduce:
1. create a new world in creative mode
2. summon a fire dragon
3. Flying up and then falling down to hit the dragon's body over and over again.
4. the crash occurs
