### ISSUE TITLE
Enchentato Mixin Moment

### ISSUE THREAD

**Issue by ANormalRaft** [MCTeamPotato/Kasualix-Issue-Tracker#81]
I don't know how mixins work and when they are applied, but I assume the mixins in one of the config files are supposed to change the behavior of the mod on a new instance (closing the game and then running the game again) of minecraft. For example, if I modify all the mixins to be false except disableEnchantmentTableUsage, the mod still modifies the loot, which is not what I want. I want only the enchantment table to be modified. I assume that this is a bug.

Forge 1.19.2 v43.2.23
Enchentato 1.1.0

**Comment by Kasualix** [comment]
Enchantato is going to be abandoned due to the significant administrative inconvenience on configuration control, it will be archived and split into a number of other mods with separate roles.
In your situation, you can use [Enchantato - Enchantment Table](https://legacy.curseforge.com/minecraft/mc-mods/enchantato-enchantment-table) module (It is currently under review)
